# Generated by Django 5.1 on 2024-08-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_avatar_remove_profile_bio_and_more'),
        ('webapp', '0004_alter_album_favorited_by_alter_photo_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='webapp.album'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_photos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='webapp.photo'),
        ),
    ]
