# Generated by Django 5.1 on 2024-08-31 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
