# Generated by Django 5.1 on 2024-08-31 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_photo_album'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
